##################################################################
# Load base lab

load File.expand_path('../../base/Vagrantfile', __FILE__)

# Overwrite base variables  

CONFIG = { 
  :dns => "8.8.8.8",
  :dc =>       {:memory => 3072, :cpus => 2, :name => "dc", :domain => "windomain.local", :ip => "192.168.38.102" },
  :srv =>      {:memory => 2048, :cpus => 2, :name => "srv", :domain => "windomain.local", :ip => "192.168.38.103"},
  :client =>   {:memory => 2048, :cpus => 1, :name => "client", :domain => "windomain.local", :ip => "192.168.38.100"},
}
##################################################################


BASE_SCRIPTS = "../base/scripts"
SYNC_FOLDER="./resources/"

Vagrant.configure("2") do |config|

  config.vm.define "dc" do |cfg|
    cfg.vm.provision "shell", path: "resources/scripts/configure-claims-gpo.ps1", preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/configure-disable-windows-defender-gpo.ps1", 
              :args => "-Domain #{CONFIG[:dc][:domain]}", preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/add_user.ps1", :args => "-Domain #{CONFIG[:dc][:domain]}", preserve_order: true, privileged: false
    cfg.vm.provision "reload"

  end

  config.vm.define "srv" do |cfg|
    cfg.vm.provision "shell", path: "resources/scripts/get-mimikatz.ps1",  preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/local_groups.ps1",  preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/enable-restricted-admin.ps1",  preserve_order: true, privileged: false
  end

end
