CONFIG = { 
  :dns => "8.8.8.8",
  :dc =>       {:memory => 3072, :cpus => 2, :name => "dc", :domain => "windomain.local", :ip => "192.168.38.102", :gw => "192.168.38.1"},
  :srv =>      {:memory => 2048, :cpus => 2, :name => "srv", :domain => "windomain.local", :ip => "192.168.38.103", :gw => "192.168.38.1"},
  :client =>   {:memory => 2048, :cpus => 1, :name => "win10", :domain => "windomain.local", :ip => "192.168.38.100", :gw => "192.168.38.1"},
}

Vagrant.configure("2") do |config|

  unless Vagrant.has_plugin?("vagrant-reload")
    raise 'vagrant-reload plugin is not installed!'
  end

  config.vm.define "dc" do |cfg|
    cfg.vm.box = "peru/windows-server-2019-standard-x64-eval"
    cfg.vm.hostname = CONFIG[:dc][:name]
    cfg.vm.boot_timeout = 600
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true

    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network  :private_network, 
                    ip: CONFIG[:dc][:ip], 
                    gateway: CONFIG[:dc][:gw], 
                    dns: CONFIG[:dns]

    cfg.vm.provision "shell", path: "resources/scripts/provision.ps1",  preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/create-forest.ps1", 
                              :args => "#{CONFIG[:dc][:ip]} #{CONFIG[:dc][:domain]} #{CONFIG[:dns]}",
                              preserve_order: true, privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "resources/scripts/configure-ou.ps1", 
                              :args => "#{CONFIG[:dc][:ip]} #{CONFIG[:dc][:name]} #{CONFIG[:dc][:domain]} ",
                              preserve_order: true, privileged: false

    cfg.vm.provider "libvirt" do |libvirt, override|
      libvirt.cpus = CONFIG[:dc][:cpus] 
      libvirt.memory = CONFIG[:dc][:memory]
      # Relax constraints on timers
      libvirt.hyperv_feature :name => 'relaxed', :state => 'on'
      # Enable virtual APIC
      libvirt.hyperv_feature :name => 'vapic', :state => 'on'

      # sync_folder is not by default on all providers
      # Furthermore, it could not be the default provider :
      # https://github.com/Cimpress-MCP/vagrant-winrm-syncedfolders/issues/11

      # We'll need vagrant-winrm-syncedfolders plugin

      override.vm.synced_folder 'resources/', '/vagrant', type: 'winrm' 
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      override.vm.box = "detectionlab/win2016"
      v.vmx["displayname"] = CONFIG[:dc][:name] 
      v.memory = CONFIG[:dc][:memory] 
      v.cpus = CONFIG[:dc][:cpus] 
      v.gui = true
      v.enable_vmrun_ip_lookup = false
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = CONFIG[:dc][:name] 
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", CONFIG[:dc][:memory] ]
      vb.customize ["modifyvm", :id, "--cpus", CONFIG[:dc][:cpus] ]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]

      override.vm.synced_folder './', '/vagrant', type: 'virtualbox'
    end

  end

  config.vm.define "srv" do |cfg|
    cfg.vm.box = "peru/windows-server-2019-standard-x64-eval"
    cfg.vm.hostname = CONFIG[:srv][:name]
    cfg.vm.boot_timeout = 600
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network  :private_network, 
                    ip: CONFIG[:srv][:ip], 
                    gateway: CONFIG[:srv][:gw], 
                    dns: CONFIG[:dns]

    cfg.vm.provision "shell", path: "resources/scripts/provision.ps1",  preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/join-domain.ps1", 
                              :args => "#{CONFIG[:srv][:domain]} #{CONFIG[:dc][:ip]}", preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/configure-rdp-smb.ps1", privileged: false
    cfg.vm.provision "reload"

    cfg.vm.provider "libvirt" do |libvirt, override|
      libvirt.cpus = CONFIG[:srv][:cpus] 
      libvirt.memory = CONFIG[:srv][:memory]
      # Relax constraints on timers
      libvirt.hyperv_feature :name => 'relaxed', :state => 'on'
      # Enable virtual APIC
      libvirt.hyperv_feature :name => 'vapic', :state => 'on'

      # sync_folder is not by default on all providers
      # Furthermore, WinRM could not be the default provider :
      # https://github.com/Cimpress-MCP/vagrant-winrm-syncedfolders/issues/11

      # We'll need vagrant-winrm-syncedfolders plugin

      override.vm.synced_folder 'resources/', '/vagrant', type: 'winrm' 
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      override.vm.box = "detectionlab/win2016"
      v.vmx["displayname"] = CONFIG[:srv][:name]
      v.memory = CONFIG[:srv][:memory]
      v.cpus = CONFIG[:srv][:cpus]
      v.gui = true
      v.enable_vmrun_ip_lookup = false
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = CONFIG[:srv][:name]
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", CONFIG[:srv][:memory]]
      vb.customize ["modifyvm", :id, "--cpus", CONFIG[:srv][:cpus]]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]

      override.vm.synced_folder './', '/vagrant', type: 'virtualbox'
    end

  end

  config.vm.define "client" do |cfg|
    cfg.vm.box = "peru/windows-10-enterprise-x64-eval"
    cfg.vm.hostname = CONFIG[:client][:name]
    cfg.vm.network  :private_network, 
                    ip: CONFIG[:client][:ip], 
                    gateway: CONFIG[:client][:gw], 
                    dns: CONFIG[:dns]

    cfg.vm.provision "shell", path: "resources/scripts/MakeWindows10GreatAgain.ps1",  preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/provision.ps1",  preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/join-domain.ps1", 
                             :args => "#{CONFIG[:client][:domain]} #{CONFIG[:dc][:ip]}", 
                             preserve_order: true, privileged: false     
    cfg.vm.provision "reload"

    cfg.vm.provider "libvirt" do |libvirt, override|
      libvirt.cpus = CONFIG[:client][:cpus] 
      libvirt.memory = CONFIG[:client][:memory]
      # Relax constraints on timers
      libvirt.hyperv_feature :name => 'relaxed', :state => 'on'
      # Enable virtual APIC
      libvirt.hyperv_feature :name => 'vapic', :state => 'on'

      # sync_folder is not by default on all providers
      # Furthermore, it could not be the default provider :
      # https://github.com/Cimpress-MCP/vagrant-winrm-syncedfolders/issues/11

      # We'll need vagrant-winrm-syncedfolders plugin

      override.vm.synced_folder 'resources/', '/vagrant', type: 'winrm' 
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      override.vm.box = "detectionlab/win10"
      v.vmx["displayname"] = CONFIG[:client][:name]
      v.vmx["gui.fullscreenatpoweron"] = "FALSE"
      v.vmx["gui.viewModeAtPowerOn"] = "windowed"
      v.memory = CONFIG[:client][:memory]
      v.cpus = CONFIG[:client][:cpus]
      v.gui = true
      v.enable_vmrun_ip_lookup = false
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = CONFIG[:client][:name]
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", CONFIG[:client][:memory]]
      vb.customize ["modifyvm", :id, "--cpus", CONFIG[:client][:cpus]]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]

      override.vm.synced_folder './', '/vagrant', type: 'virtualbox'
    end
  end
end
